### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by cedkeChat** [u08614s/HelloWorldDrawtextSample#1]
when I change the text to hexadecimal it gives me weird characters can you help me how I could change the text please!!!!

**Comment by ghost** [comment]
Convert like this

![2022-10-19_21-10](https://user-images.githubusercontent.com/90534409/196832933-79f549d1-2648-4430-be8d-e2bae609c9f2.png)

Most likely you got an output like

`.H.e.l.l.o. .W.o.r.l.d.!` instead of it being a clean `Hello World!`. Just make sure you use the Unicode setting as it's proper format for Hex memory. Once you convert it (or any other string) You can format it in the .long format, the same as in the ASM. For example `CedkeChat! :)` converted properly would give you the string `004300650064006B0065004300680061007400210020003A0029` which can then be formatted into .long like so

```
.long 0x00430065
.long 0x0064006B
.long 0x00650043
.long 0x00680061
.long 0x00740021
.long 0x0020003A
.long 0x00290000
.long 0
```

**Comment by u08614s** [comment]
thanks
